Huge workaround for checking IP presence

diff --git a/skuf_src/init(untuned) b/skuf_src/init(untuned)
--- a/skuf_src/init(untuned)
+++ b/skuf_src/init(untuned)
@@ -118,8 +118,121 @@ bring_lo_up() {
     ip link set lo up
 }
 
+get_smbaddr_type() {
+    local so_this_is
+
+    if echo "$smbaddr" | grep -q -E -o '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
+        case "$smbaddr" in
+            "169.254."*)
+                so_this_is=ipv4ll
+            ;;
+            *)
+                so_this_is=ipv4
+            ;;
+        esac
+    elif echo "$smbaddr" | grep -q -E -o '^(::)?[0-9a-fA-F]{1,4}(::?[0-9a-fA-F]{1,4}){1,7}(::)?(%[0-9a-zA-Z_-]+)?$'; then
+        case "$smbaddr" in
+            [fF][eE]80::*)
+                so_this_is=slaac
+            ;;
+            *)
+                so_this_is=ipv6
+            ;;
+        esac
+    elif echo "$smbaddr" | grep -q -o '.*\.local$'; then
+        so_this_is=zeroconf
+    else
+        so_this_is=domain
+    fi
+
+    echo "$so_this_is"
+}
+
+check_dhcpcd() {
+    # brain-aneurysm.mp3
+    local dump i ipv4_grep ipv6ra_grep dhcpv6_grep ipv4=0 ipv6=0 slaac=0 ipv4ll=0
+
+    if ! dump="$(dhcpcd -U)"; then
+        echo "Error: failed to dump DHCP lease"
+        return 1
+    fi
+
+    if ! echo "$dump" | grep -q "[^[:space:]]"; then
+        echo "dhcpcd failed: no network interface has been used"
+        return 1
+    fi
+
+    if ! echo "$dump" | grep -q -o "^ifcarrier=[\"']?up[\"']?$"; then
+        echo "dhcpcd failed: no working carrier found"
+        return 1
+    fi
+
+    ipv4_grep="$(echo "$dump"   | grep -E -o "^ip_address=[\"']?..*[\"']?$")"
+    ipv6ra_grep="$(echo "$dump" | grep -E -o "^nd[0-9]+_addr[0-9]+=[\"']?..*[\"']?$")"
+    dhcpv6_grep="$(echo "$dump" | grep -E -o "^dhcp6_ia_na[0-9]+_ia_addr[0-9]+=[\"']?..*[\"']?$")"
+
+    while read -r i; do
+        i="${i#*=}"
+        i="${i//[\"\']/}"
+        case "$i" in
+            "") :                  ;;
+            "169.254."*) ipv4ll=1  ;;
+            *) ipv4=1              ;;
+        esac
+    done <<GREP
+$ipv4_grep
+GREP
+
+    while read -r i; do
+        i="${i#*=}"
+        i="${i//[\"\']/}"
+        case "$i" in
+            "") :                  ;;
+            [fF][eE]80::*) slaac=1 ;;
+            *) ipv6=1              ;;
+        esac
+    done <<GREP
+$ipv6ra_grep
+$dhcpv6_grep
+GREP
+
+    case "$type_of_smbaddr" in
+        "ipv4"|"ipv4ll")
+                if [ $ipv4   -gt 0 ] || \
+                   [ $ipv4ll -gt 0 ]; then
+                    return 0
+                else
+                    echo "dhcpcd failed: IPv4 address not received"
+                    return 1
+                fi
+        ;;
+        "ipv6"|"slaac")
+                if [ $ipv6  -gt 0 ] || \
+                   [ $slaac -gt 0 ]; then
+                    return 0
+                else
+                    echo "dhcpcd failed: IPv6 address not received"
+                    return 1
+                fi
+        ;;
+        "zeroconf"|"domain")
+                if [ $ipv4   -gt 0 ] || \
+                   [ $ipv6   -gt 0 ] || \
+                   [ $slaac  -gt 0 ] || \
+                   [ $ipv4ll -gt 0 ]; then
+                    return 0
+                else
+                    echo "dhcpcd failed: IP address not received"
+                    return 1
+                fi
+        ;;
+    esac
+
+    return 1
+}
+
 get_dhcp() {
-    local i interface x="0"
+    local i interface x="0" sleepsec=5 fail2start=0
 
     for i in /sys/class/net/*; do
         interface="${i##*/}"
@@ -136,26 +249,50 @@ get_dhcp() {
     done
 
     if [ $x -eq 0 ]; then
-        echo "Error: no wired network interface found. Good luck."
+        echo "Error: no wired network interface found."
         # shellcheck disable=SC2086
         run_hookfunctions 'run_emergencyhook' 'emergency hook' $EMERGENCYHOOKS
         launch_interactive_shell --exec
     fi
 
-    if ! dhcpcd -q --allowinterfaces 'eth* en*'; then
-        # We should try again (for buggy IPv6 RA)
+    type_of_smbaddr="$(get_smbaddr_type)"
+    case "$type_of_smbaddr" in "zeroconf"|"ipv4ll")
+        sleepsec=10
+        sed -i 's/^noipv4ll$/# noipv4ll #/' /etc/dhcpcd.conf ;;
+    esac
+    ###################################
+    if dhcpcd -q --allowinterfaces 'eth* en*'; then
+        msg "-> dhcpcd forked. Sleeping $sleepsec seconds..."
+        sleep "$sleepsec"
+    else
+        fail2start=1
+    fi
+    ###################################
+    if [ $fail2start -eq 1 ] || ! check_dhcpcd; then
+        # We should try again
         msg "-> dhcpcd failed. Trying again..."
-        sleep 3
+        sleep 1
+        dhcpcd -q -q -x
+        fail2start=0
+        # For buggy IPv6 RA
         sed -i 's/^# ipv6ra_fork #$/ipv6ra_fork/' /etc/dhcpcd.conf
-        if ! dhcpcd -q --allowinterfaces 'eth* en*'; then
+        ###################################
+        if dhcpcd -q --allowinterfaces 'eth* en*'; then
+            msg "-> dhcpcd forked. Sleeping $sleepsec seconds..."
+            sleep "$sleepsec"
+        else
+            fail2start=1
+        fi
+        ###################################
+        if [ $fail2start -eq 1 ] || ! check_dhcpcd; then
+            case "$type_of_smbaddr" in "zeroconf"|"ipv4ll")
+                sed -i 's/^# noipv4ll #$/noipv4ll/' /etc/dhcpcd.conf ;;
+            esac
             sed -i 's/^ipv6ra_fork$/# ipv6ra_fork #/' /etc/dhcpcd.conf
             echo "Failed to acquire DHCP address."
             launch_interactive_shell
         fi
     fi
-
-    msg "-> IP address received. Sleeping 5 seconds..."
-    sleep 5
 }
 
 renice_dhcpcd() {
