Add support for re-entering SAMBA credentials if mount failed

diff --git a/skuf_src/kinit(untuned) b/skuf_src/kinit(untuned)
--- a/skuf_src/kinit(untuned)
+++ b/skuf_src/kinit(untuned)
@@ -17,6 +17,12 @@ newrootmountopts="$sep"
 newrootfsck="$sep"
 smbmode="ro"
 
+re_smbusername=
+re_smbpassword=
+uq_smbvolumepath=
+uq_smbvolumefilename=
+uq_smbswapfilename=
+
 kernelopts="$sep"
 
 kernelpath="$sep"
@@ -54,12 +60,28 @@ check_smbusername() {
     return 0
 }
 
+check_smbusername2() {
+    if [ "$re_smbusername" == "$sep" ]; then
+        return 1
+    fi
+
+    return 0
+}
+
 check_smbpassword() {
     if [ "$smbpassword" == "$sep" ]; then
         return 1
     fi
     if [ -z "$smbpassword" ]; then
         echo -e "  \e[1;31m! Password missing\e[0m"
+        return 1
+    fi
+
+    return 0
+}
+
+check_smbpassword2() {
+    if [ "$re_smbpassword" == "$sep" ]; then
         return 1
     fi
 
@@ -91,7 +113,12 @@ read_smbpassword() {
         fi
     done
 
-    smbpassword="$password"
+    if [ "$1" == "retry" ]; then
+        re_smbpassword="$password"
+    else
+        smbpassword="$password"
+    fi
+
 }
 
 check_smbaddr() {
@@ -363,28 +390,6 @@ user_read() {
     ___ _
 }
 
-setup_sambaopts() {
-    local sambaoptsx
-
-    echo "[] Building and encrypting /proc/cmdline"
-
-    sambaoptsx="${smbaddr}${sep}${smbport}${sep}${smbversion}${sep}${smbdomain}${sep}${smbusername}${sep}${smbpassword}${sep}${smbvolumepath}${sep}${smbvolumefilename}${sep}${smbswapfilename}${sep}${smbmountopts}${sep}${newrootmountopts}${sep}${newrootfsck}"
-    # SKUF_OPENSSL_ENC #
-    sambaoptsx="$(echo -n "$sambaoptsx" | openssl enc -e -aes-256-cbc -salt -iter 1234 -base64 -A -k '12345678' -in - -out -)" # SKUF_OPENSSL_ENC_RM #
-    sambaoptsx="${sambaoptsx//=/%}"
-    sambaoptsx="${sambaoptsx:10}"
-
-    # SKUF_ENC_TUNE #
-
-    sambaopts="fuckmyass=${sambaoptsx}:"
-}
-
-setup_kernelopts() {
-    if [ -n "$kernelopts" ]; then
-        kernelopts="$kernelopts "
-    fi
-}
-
 bring_lo_up() {
     echo "[] Bringing UP 'lo' network interface"
     ip link set lo up
@@ -449,6 +454,7 @@ get_dhcp() {
 quirk_vars() {
     echo "[] Quirking variables"
 
+    uq_smbvolumepath="$smbvolumepath"
     smbvolumepath="${smbvolumepath//@u@/${smbusername/@*/}}"
     smbvolumepath="${smbvolumepath//@fu@/${smbusername}}"
     case "$smbvolumepath" in
@@ -460,12 +466,14 @@ quirk_vars() {
         *)       smbvolumepath="/${smbvolumepath}/" ;;
     esac
 
+    uq_smbvolumefilename="$smbvolumefilename"
     smbvolumefilename="${smbvolumefilename//@u@/${smbusername/@*/}}"
     smbvolumefilename="${smbvolumefilename//@fu@/${smbusername}}"
     case "$smbvolumefilename" in
         "/"*) smbvolumefilename="${smbvolumefilename#/}" ;;
     esac
 
+    uq_smbswapfilename="$smbswapfilename"
     smbswapfilename="${smbswapfilename//@u@/${smbusername/@*/}}"
     smbswapfilename="${smbswapfilename//@fu@/${smbusername}}"
     case "$smbswapfilename" in
@@ -473,6 +481,65 @@ quirk_vars() {
     esac
 
     return 0
+}
+
+retry_samba() {
+    local ylw="$(echo -e '\e[1;33m')"
+    local i x="1"
+    i="$1"
+
+    if [ -z "$i" ] || [ -n "${i//[0-9]/}" ]; then
+        i="2"
+    fi
+
+    echo -e "\e[0;31mFailed to mount SAMBA share\e[0m! \e[0;36mEnter your credentials\e[0m \e[1magain\e[0m."
+    echo -e "Press \e[1;36m[Enter]\e[0m to use your old username/password"
+
+    while [ $x -le $i ]; do
+        re_smbusername="$sep"
+        re_smbpassword="$sep"
+        smbvolumepath="$uq_smbvolumepath"
+        smbvolumefilename="$uq_smbvolumefilename"
+        smbswapfilename="$uq_smbswapfilename"
+        while ! check_smbusername2; do
+            read -e -p "Login:                  $ylw" \
+                    re_smbusername
+            ___
+        done
+
+        if [ -n "$re_smbusername" ]; then
+            smbusername="$re_smbusername"
+        fi
+
+        while ! check_smbpassword2; do
+                    read_smbpassword retry
+            ___ _
+        done
+
+        if [ -n "$re_smbpassword" ]; then
+            smbpassword="$re_smbpassword"
+        fi
+
+        quirk_vars
+
+        finalusername="username=$smbusername,"
+        [ -z "$smbport"      ] || finalport="port=$smbport,"
+        [ -z "$smbversion"   ] || finalversion="vers=$smbversion,"
+        [ -z "$smbdomain"    ] || finaldomain="domain=$smbdomain,"
+        [ -z "$smbmountopts" ] || finalmountopts="$smbmountopts,"
+
+        echo "[] Remounting SAMBA"
+
+        if PASSWD="$smbpassword" mount -t cifs -o "${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}" "//${smbaddr}${smbvolumepath}" /samba; then
+            return 0
+        else
+            echo "Failed to mount SAMBA share!"
+            x=$(( x + 1 ))
+            continue
+        fi
+    done
+
+    return 1
 }
 
 mount_samba() {
@@ -485,9 +552,11 @@ mount_samba() {
     echo "[] Mounting SAMBA"
 
     if ! PASSWD="$smbpassword" mount -t cifs -o "${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}" "//${smbaddr}${smbvolumepath}" /samba; then
-        echo "Failed to mount SAMBA share!"
-        echo "PASSWD=\"$smbpassword\" mount -t cifs -o \"${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}\" \"//${smbaddr}${smbvolumepath}\" /samba"
-        launch_interactive_shell
+        if ! retry_samba 2; then
+            echo "Failed to mount SAMBA share!"
+            echo "PASSWD=\"$smbpassword\" mount -t cifs -o \"${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}\" \"//${smbaddr}${smbvolumepath}\" /samba"
+            launch_interactive_shell
+        fi
     fi
 }
 
@@ -556,6 +625,28 @@ mount_newroot() {
             echo "mount -o \"ro${newrootmountoptsx}\" /samba/\"${smbvolumefilename}\" /new_root"
             launch_interactive_shell
         fi
+    fi
+}
+
+setup_sambaopts() {
+    local sambaoptsx
+
+    echo "[] Building and encrypting /proc/cmdline"
+
+    sambaoptsx="${smbaddr}${sep}${smbport}${sep}${smbversion}${sep}${smbdomain}${sep}${smbusername}${sep}${smbpassword}${sep}${uq_smbvolumepath}${sep}${uq_smbvolumefilename}${sep}${uq_smbswapfilename}${sep}${smbmountopts}${sep}${newrootmountopts}${sep}${newrootfsck}"
+    # SKUF_OPENSSL_ENC #
+    sambaoptsx="$(echo -n "$sambaoptsx" | openssl enc -e -aes-256-cbc -salt -iter 1234 -base64 -A -k '12345678' -in - -out -)" # SKUF_OPENSSL_ENC_RM #
+    sambaoptsx="${sambaoptsx//=/%}"
+    sambaoptsx="${sambaoptsx:10}"
+
+    # SKUF_ENC_TUNE #
+
+    sambaopts="fuckmyass=${sambaoptsx}:"
+}
+
+setup_kernelopts() {
+    if [ -n "$kernelopts" ]; then
+        kernelopts="$kernelopts "
     fi
 }
 
