Make error handling more verbose

diff --git a/skuf_src/kinit(untuned) b/skuf_src/kinit(untuned)
--- a/skuf_src/kinit(untuned)
+++ b/skuf_src/kinit(untuned)
@@ -486,7 +486,7 @@ mount_samba() {
 
     if ! PASSWD="$smbpassword" mount -t cifs -o "${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}" "//${smbaddr}${smbvolumepath}" /samba; then
         echo "Failed to mount SAMBA share!"
-        echo "PASSWD=$smbpassword mount -t cifs -o ${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode} //${smbaddr}${smbvolumepath} /samba"
+        echo "PASSWD=\"$smbpassword\" mount -t cifs -o \"${finalusername}${finalport}${finaldomain}${finalmountopts}${finalversion}${smbmode}\" \"//${smbaddr}${smbvolumepath}\" /samba"
         launch_interactive_shell
     fi
 }
@@ -547,11 +547,13 @@ mount_newroot() {
     if [ "$(blkid -o value -s TYPE /samba/"${smbvolumefilename}")" == "ext4" ]; then
         if ! mount -o "ro,noload${newrootmountoptsx}" /samba/"${smbvolumefilename}" /new_root; then
             echo "Failed to mount /new_root!"
+            echo "mount -o \"ro,noload${newrootmountoptsx}\" /samba/\"${smbvolumefilename}\" /new_root"
             launch_interactive_shell
         fi
     else
         if ! mount -o "ro${newrootmountoptsx}" /samba/"${smbvolumefilename}" /new_root; then
             echo "Failed to mount /new_root!"
+            echo "mount -o \"ro${newrootmountoptsx}\" /samba/\"${smbvolumefilename}\" /new_root"
             launch_interactive_shell
         fi
     fi
@@ -569,7 +571,11 @@ prepare_kexec() {
     echo "[] Preparing kexec"
     echo "[] Loading kernel and initramfs into RAM"
 
-    /switch/bin/kexec -l "/new_root${kernelpath}" --initrd="/new_root${initramfspath}" --command-line="${kernelopts}${sambaopts}" --console-vga --reset-vga || launch_interactive_shell
+    if ! /switch/bin/kexec -l "/new_root${kernelpath}" --initrd="/new_root${initramfspath}" --command-line="${kernelopts}${sambaopts}" --console-vga --reset-vga; then
+        echo "Failed to load kernel and initramfs to RAM!"
+        echo "/switch/bin/kexec -l \"/new_root${kernelpath}\" --initrd=\"/new_root${initramfspath}\" --command-line=\"${kernelopts}${sambaopts}\" --console-vga --reset-vga"
+        launch_interactive_shell
+    fi
 }
 
 prepare_switch() {
